language: rust

rust:
    - nightly

cache: cargo

before_script:
  - (cargo install rustfmt || true)
  - (cargo install xargo || true)
  - PATH=$PATH:~/.cargo/bin

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm
      - cmake
    sources:
      - kalakris-cmake

script: make
