language: rust

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

branches:
  except:
    # Used by bors
    - staging.tmp

rust:
    - nightly

os:
  - linux
  - osx

cache: cargo

addons:
  apt:
    packages:
      - qemu-system-x86

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install qemu; fi

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - cargo install-update -a

script:
  - bootimage build
  - cargo test
  - bootimage test
