language: rust

rust:
    - nightly

cache: cargo

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (cargo install rustfmt || true)
  - (cargo install xargo || true)

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm

script: make
