title = "Writing an OS in Rust"
base_url = "https://os.phil-opp.com"
description = "This blog series creates a small operating system in the Rust programming language. Each post is a small tutorial and includes all needed code."

highlight_code = true
highlight_theme = "visual-studio-dark"
generate_rss = true

languages = [
    { code = "zh-CN" }, # Chinese (simplified)
    { code = "zh-TW" }, # Chinese (tradictional)
]

ignored_content = ["*/README.md"]

[extra]
subtitle = "Philipp Oppermann's blog"
author = { name = "Philipp Oppermann" }
